// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Equity.ProperyListRequest = (function(_super) {
  __extends(ProperyListRequest, _super);

  function ProperyListRequest(id) {
    this.id = id;
    this._createScript = __bind(this._createScript, this);
    this.send = __bind(this.send, this);
    this.url = "equityone.net:80";
  }

  ProperyListRequest.prototype.send = function() {
    var response, script;
    script = this._createScript();
    return response = bridge.executeScript(script);
  };

  ProperyListRequest.prototype._createScript = function() {
    return "new ExternalObject('lib:webaccesslib'); var url = 'http://www.equityone.net/tools/sitexmlgen.aspx'; var http = new HttpConnection(url); var path = '" + main.path + "/exports/data/xml/property_list.xml'; var file = new File(path); http.response = file; http.execute(); http.response.close(); http.close();";
  };

  return ProperyListRequest;

})(Array);
