// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Equity.Main = (function() {
  function Main() {
    this._onExported = __bind(this._onExported, this);
    this.init = __bind(this.init, this);
    this.root = new File($.fileName).parent.parent.parent;
    this.path = this.root.absoluteURI;
  }

  Main.prototype.init = function() {
    this.errors = new Equity.Errors();
    this.folders = new Equity.Folders();
    this.properties = new Equity.Properties();
    if (!(this.properties.list.length > 0)) {
      return;
    }
    return this.properties["export"](this._onExported);
  };

  Main.prototype._onExported = function() {
    this.errors.log();
    this.errors.alert();
    return bridge.quit();
  };

  return Main;

})();
