// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Equity.Property = (function() {
  function Property(id, path) {
    this.id = id;
    this.path = path;
    this._onXmlData = __bind(this._onXmlData, this);
    this["export"] = __bind(this["export"], this);
    this.file = new File(this.path);
  }

  Property.prototype["export"] = function(callback) {
    var error;
    this.callback = callback;
    if (!this.file.exists) {
      error = "Could not find design file for property " + property.id;
      main.errors.push(error);
      this.callback();
      return;
    }
    app.userInteractionLevel = UserInteractionLevel.DONTDISPLAYALERTS;
    app.open(this.file);
    this.doc = app.activeDocument;
    this.xmlData = new Equity.XmlData(this);
    return this.xmlData["export"](this._onXmlData);
  };

  Property.prototype._onXmlData = function() {
    this.pdfImages = new Equity.PdfImages(this);
    this.webImages = new Equity.WebImages(this);
    this.svgData = new Equity.SvgData(this);
    this.jsonData = new Equity.JsonData(this);
    this.doc.close(SaveOptions.DONOTSAVECHANGES);
    return this.callback();
  };

  return Property;

})();
