// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Equity.PropertyList = (function(_super) {
  __extends(PropertyList, _super);

  function PropertyList() {
    var compare, file, id, parts, path, type, _i, _len, _ref;
    this.paths = File.openDialog("Choose Your File(s)", ["*.ai"], true);
    if (!this.paths) {
      return this;
    }
    _ref = this.paths;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      path = _ref[_i];
      path = path.toString();
      parts = path.split("/");
      file = parts[parts.length - 1];
      parts = file.split(".");
      if (parts.length !== 2) {
        continue;
      }
      id = parts[0];
      type = parts[1];
      if (type !== "ai") {
        continue;
      }
      this.push(new Equity.Property(id, path));
    }
    compare = function(a, b) {
      return a.id - b.id;
    };
    this.sort(compare);
  }

  return PropertyList;

})(Array);
