// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Equity.Properties = (function() {
  function Properties() {
    this._next = __bind(this._next, this);
    this["export"] = __bind(this["export"], this);
    this.index = -1;
    this.list = new Equity.PropertyList();
  }

  Properties.prototype["export"] = function(callback) {
    this.callback = callback;
    return this._next();
  };

  Properties.prototype._next = function() {
    var property;
    if (++this.index === this.list.length) {
      this.callback();
      return;
    }
    property = this.list[this.index];
    return property["export"](this._next);
  };

  return Properties;

})();
