// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Equity.PropertyData = (function() {
  function PropertyData(id) {
    this.id = id;
    this._createScript = __bind(this._createScript, this);
    this.send = __bind(this.send, this);
    this.url = "equityone.net:80";
  }

  PropertyData.prototype.send = function() {
    var response, script;
    script = this._createScript();
    return response = bridge.executeScript(script);
  };

  PropertyData.prototype._createScript = function() {
    return "new ExternalObject('lib:webaccesslib'); var url  = 'http://www.equityone.net/tools/xmlgen.aspx?ID=" + this.id + "'; var http = new HttpConnection(url); http.execute(); http.close(); var url  = 'http://www.equityone.net/tools/p_" + this.id + ".xml'; var http = new HttpConnection(url); var path = '" + main.path + "/exports/data/xml/" + this.id + ".xml'; var file = new File(path); http.response = file; http.execute(); http.response.close(); http.close();";
  };

  return PropertyData;

})();
