// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Equity.SvgData = (function() {
  function SvgData(property) {
    this.property = property;
    this._export = __bind(this._export, this);
    this._setupUnits = __bind(this._setupUnits, this);
    this._setupLayers = __bind(this._setupLayers, this);
    this.path = "" + main.path + "/exports/data/svg/" + this.property.id + ".svg";
    this.opts = new ExportOptionsSVG();
    this.opts.preserveEditability = false;
    this.opts.embedRasterImages = true;
    this.opts.embedAllFonts = false;
    this._setupLayers();
    this._setupUnits();
    this._export();
  }

  SvgData.prototype._setupLayers = function() {
    var i, layer, _i, _ref, _results;
    _results = [];
    for (i = _i = _ref = this.property.doc.layers.length - 1; _ref <= -1 ? _i < -1 : _i > -1; i = _ref <= -1 ? ++_i : --_i) {
      layer = this.property.doc.layers[i];
      if (layer.name !== "Hotspots") {
        layer.visible = true;
        layer.locked = false;
        _results.push(layer.remove());
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  SvgData.prototype._setupUnits = function() {
    var item, _i, _len, _ref, _results;
    _ref = this.property.doc.pathItems;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      if (item.parent.name === "Hotspots") {
        _results.push(item.name = "uid" + _i + "|" + item.name);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  SvgData.prototype._export = function() {
    var file;
    file = new File(this.path);
    return this.property.doc.exportFile(file, ExportType.SVG, this.opts);
  };

  return SvgData;

})();
