// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Equity.WebImages = (function() {
  function WebImages(property) {
    this.property = property;
    this._hideLayer = __bind(this._hideLayer, this);
    this._showLayer = __bind(this._showLayer, this);
    this._exportBackground = __bind(this._exportBackground, this);
    this._exportForeground = __bind(this._exportForeground, this);
    this._initLayers = __bind(this._initLayers, this);
    this._initLayers();
    this._exportForeground();
    this._exportBackground();
  }

  WebImages.prototype._initLayers = function() {
    this._hideLayer("Foreground");
    this._hideLayer("Hotspots");
    return this._hideLayer("Background");
  };

  WebImages.prototype._exportForeground = function() {
    var file, opts, path;
    this._showLayer("Foreground");
    path = "" + main.path + "/exports/images/web/" + this.property.id + "-foreground.png";
    opts = new ExportOptionsPNG24();
    opts.antiAliasing = true;
    opts.transparency = true;
    opts.artBoardClipping = true;
    file = new File(path);
    return this.property.doc.exportFile(file, ExportType.PNG24, opts);
  };

  WebImages.prototype._exportBackground = function() {
    var file, opts, path;
    this._hideLayer("Foreground");
    this._showLayer("Hotspots");
    this._showLayer("Background");
    path = "" + main.path + "/exports/images/web/" + this.property.id + "-background.jpg";
    opts = new ExportOptionsPNG24();
    opts.antiAliasing = true;
    opts.transparency = false;
    opts.artBoardClipping = true;
    file = new File(path);
    return this.property.doc.exportFile(file, ExportType.PNG24, opts);
  };

  WebImages.prototype._showLayer = function(name) {
    var i, layer, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = this.property.doc.layers.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      layer = this.property.doc.layers[i];
      layer.locked = false;
      if (layer.name === name) {
        _results.push(layer.visible = true);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  WebImages.prototype._hideLayer = function(name) {
    var i, layer, _i, _ref, _results;
    _results = [];
    for (i = _i = 0, _ref = this.property.doc.layers.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      layer = this.property.doc.layers[i];
      layer.locked = false;
      if (layer.name === name) {
        _results.push(layer.visible = false);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  return WebImages;

})();
